version: "3.8"
services:
  db:
    build: ./postgresdb
    container_name: postgres_container
    hostname: postgres_container
    ports: 
      - "5432:5432"
    environment: 
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=webcalls"
    volumes:
      - dbdata:/var/lib/postgresql
  api:
    depends_on: 
      - db
    build: ./api
    image: goapiscraper_image
    container_name: goapiscraper_container
    ports: 
      - "8081:9000"
volumes:
   dbdata: {}
