openapi: 3.0.0
info:
  title: Go Scraping API
  description: An API for scraping web titles using multiple goroutines
  version: 1.0.0
  contact:
    name: George Gale
    email: gmgale@icloud.com
servers:
  - url: http://localhost:8080/
    
  

paths:
  "/api/{Id=threads}":
    get:
      summary: Prints titles of web pages to screen.
      description: User defined threds/Go Routines as argument.
      parameters:
        - name: Id=threads
          in: path
          required: true
          description: Number of web scraping Go Routines to run concurrenty.
          schema:
            type : integer
      responses: 
        '200':
          description: OK 1234
                      