openapi: 3.0.0
info:
  title: Go API Scraping
  description: A web API for scraping web titles using concurrent Goroutines
  version: 1.0.0
  contact:
    name: George Gale
    email: gmgale@icloud.com
servers:
  - url: http://localhost:8080/
    
paths:
  "/api":
    get:
      summary: Splash screen with basic API instructions.
      responses:
          '200':
            description: Responded OK - 200
  "/api/{Id=threads}":
    get:
      summary: Prints titles of web pages to screen.
      description: User defined threds/Goroutines as argument.
      parameters:
        - name: Id=threads
          in: path
          required: true
          description: Number of web scraping Goroutines to run concurrently. Cannot exceed number of URLS.
          schema:
            type : integer
          
      responses: 
        '200':
          description: Responded OK - 200
          