version: "3.8"
services:
  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    network_mode: bridge
    ports: 
      - "5432:5432"
    environment: 
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=tide_server"
    volumes:
      - dbdata:/var/lib/postgresql
  api:
    build: .\
    image: goapiscraper_image
    container_name: goapiscraper_container
    ports: 
      - "8080:8080"
volumes:
   dbdata: {}
   