FROM golang:latest
ADD . /go/src/github.com/gmgale/result_task/src
WORKDIR /go/src/github.com/gmgale/result_task/src
RUN go get github.com/gorilla/mux
RUN go install

FROM alpine:latest
COPY --from=0 /go/bin /api
WORKDIR /api
EXPOSE 8080
CMD [ "./goapiscraper" ]
