FROM golang:latest
ADD . /go/src/github.com/gmgale/result_task/src
WORKDIR /go/src/github.com/gmgale/result_task/src
RUN go get github.com/gorilla/mux
RUN go install

FROM alpine:latest
WORKDIR /root/
COPY --from=0 /go/src/github.com/gmgale/result_task/src .
CMD [ "./goapiscraper.exe" ]
EXPOSE 8080:9000
